---
# tasks file for lighthouse-role
- name: Create lighthouse config
  become: true
  template:
    src: lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: Reload nginx service
