---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 51.250.6.169
      ansible_private_key_file: ~/.ssh/id_rsa

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 51.250.10.84
      ansible_private_key_file: ~/.ssh/id_rsa

lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 62.84.113.211
      ansible_private_key_file: ~/.ssh/id_rsa