---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 51.250.69.183
      ansible_private_key_file: ~/.ssh/id_rsa

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 62.84.124.215
      ansible_private_key_file: ~/.ssh/id_rsa
