---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 89.169.135.136
      ansible_private_key_file: ~/.ssh/id_rsa

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 89.169.137.254
      ansible_private_key_file: ~/.ssh/id_rsa

lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 89.169.145.177
      ansible_private_key_file: ~/.ssh/id_rsa